### ISSUE TITLE
When a rule is matched more than once easybake crashes

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-easybake#48]
When a rule is matched more than once an exception occurs 💥  . Not a critical problem, but hunting it down took longer than I'd expected (~2hrs).

```css
div::outside,
div::outside {
  content: "hello"; 
}
```

```html
<body>
  <div/>
</body>
```

```
Traceback (most recent call last):
  File "/Users/phil/github/cnx/cnx-recipes/venv/bin/cnx-easybake", line 9, in <module>
    load_entry_point('cnx-easybake==0.7.0', 'console_scripts', 'cnx-easybake')()
  File "/Users/phil/github/cnx/cnx-recipes/venv/lib/python2.7/site-packages/cnxeasybake/scripts/main.py", line 81, in main
    args.coverage_file)
  File "/Users/phil/github/cnx/cnx-recipes/venv/lib/python2.7/site-packages/cnxeasybake/scripts/main.py", line 21, in easybake
    oven.bake(html_doc, last_step)
  File "/Users/phil/github/cnx/cnx-recipes/venv/lib/python2.7/site-packages/cnxeasybake/oven.py", line 251, in bake
    grouped_insert(target, value)
  File "/Users/phil/github/cnx/cnx-recipes/venv/lib/python2.7/site-packages/cnxeasybake/oven.py", line 1268, in grouped_insert
    t.parent.insert(t.parent.index(t.tree), value)
  File "src/lxml/lxml.etree.pyx", line 1233, in lxml.etree._Element.index (src/lxml/lxml.etree.c:53901)
ValueError: Element is not a child of this node.
```

**Comment by reedstrm** [comment]
Oh, this is a good one. Excellent minimal reproduction case.

**Comment by reedstrm** [comment]
So, what should be the expected behavior in this case?

**Comment by reedstrm** [comment]
This happens because the targeted node has changed parents, do to the `::outside` creating a new, interstitial node. I presume the expected output would be something like:
```
<body>
  <div>
    <div>
      <div/>
      hello  
    </div>
    hello
  </div>
</body>
```

**Comment by philschatz** [comment]
Oh, I didn't remember that this Issue was created when I asked the same question on #59 😊  (they're now linked together ; )


I guess the behavior I would expect is that the resulting HTML would be:

```
<body>
  <div>Hello</div>
</body>
```

No?

**Comment by reedstrm** [comment]
No. That's not how any of the other pseudo-elements work. We should make this not-crash, and match the behavior of the others. Then separately continue discussion about changing behavior of all of them.

**Comment by philschatz** [comment]
okies, merged 😄
