### ISSUE TITLE
Building intro-business guide dumps core

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-easybake#90]
Travis log: https://travis-ci.org/Connexions/cnx-recipes/builds/388838856?utm_source=github_status&utm_medium=notification

```
cnx-easybake WARNING TopTitleContent blank string
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/cnx-easybake", line 11, in <module>
    load_entry_point('cnx-easybake', 'console_scripts', 'cnx-easybake')()
  File "/home/travis/virtualenv/python2.7.14/src/cnxeasybake/cnxeasybake/scripts/main.py", line 88, in main
    args.coverage_file, args.use_repeatable_ids)
  File "/home/travis/virtualenv/python2.7.14/src/cnxeasybake/cnxeasybake/scripts/main.py", line 20, in easybake
    oven.bake(html_doc, last_step)
  File "/home/travis/virtualenv/python2.7.14/src/cnxeasybake/cnxeasybake/oven.py", line 317, in bake
    grouped_insert(target, value)
  File "/home/travis/virtualenv/python2.7.14/src/cnxeasybake/cnxeasybake/oven.py", line 1432, in grouped_insert
    if n == t.tree][0]
IndexError: list index out of range
./script/generate-guide: ERROR: could not run [cnx-easybake --coverage-file ./tmp//intro-business/mixins/styleguide/page.table.raw.xhtml-temp1-baked.xhtml.lcov --use-repeatable-ids ./recipes/output/intro-business.css ./tmp//intro-business/mixins/styleguide/page.table.raw.xhtml ./tmp//intro-business/mixins/styleguide/page.table.raw.xhtml-temp1-baked.xhtml]
./script/test: ERROR: could not run [./script/generate-guide intro-business]
The command "kcov ./coverage/ ./script/ci" exited with 111.
```

**Comment by tomjw64** [comment]
A short example of what causes failure:
This markup
```html
<html>
  <div class="select-me">
    <span>Text</span>
  </div>
</html>
```
baked with
```css
.select-me::outside { content: pending(empty-bucket); }
.select-me::outside { content: content(); }
```
yields the same error. After the first `::outside`, `.select-me` is removed from its parent because its content was set to an empty group. On the second `::outside`, `.select-me`'s parent is found, but it no longer has `.select-me` as a descendant, causing an IndexError. The change in PR #91 catches and warns about this behavior.
